name = "TheNaNTrap"
uuid = "6617227e-8b0f-44b8-a378-54901d3fdf2e"
authors = ["Julia Computing", "Matt Bauman <mbauman@juliacomputing.com>", "and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
